FROM python:latest

WORKDIR /usr/bot

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

COPY docker/wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh